### ISSUE TITLE
Following the instructions results in errors

### ISSUE THREAD

**Issue by T-Fletcher** [govCMS/govcms7-scaffold-paas#5] opened 2019-09-18 06:21 UTC
I just tested spinning up a local `govcms-scaffolding-paas` instance via Docker in both Windows and MacOS, and it falls over at Step 3 of the Project Setup instructions in `README.md`. 

@fubarhouse noted that this repo does not include a copy of Drupal 7 in the `docroot`, which is actually a requirement for the govCMS profile to install successfully.

After extracting Drupal 7 into the `docroot`, and replacing the `sites/default/files/settings.php` with the version included in this repo, the installation command instead throws PHP errors when attempting to run any Drush commands. 

Can the instructions please be updated to allow users following them to end up with a working site? Alternately, if this isn't the point of this repo, can the instructions please state as much?

**Comment by T-Fletcher** [comment] 2019-09-23 01:32
See https://github.com/govCMS/govcms7-scaffold-paas/pull/7

**Comment by fubarhouse** [comment] 2019-09-23 12:03
@T-Fletcher,

I've isolated the cause and provided a fix for this.

In the meantime, you can find the fix in #8 - at least this way the scaffold can benefit from all the goodness of this repository without making any sacrifices to get it working 😊

**Closed** 2024-03-24 01:17 UTC
